// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1YZbo58XvQNJMsNHZskvqkRVqA8nr018',
    appId: '1:1088035788364:android:c5373a15ddf1315c22c6e9',
    messagingSenderId: '1088035788364',
    projectId: 'movie-finder-devbyaryan',
    storageBucket: 'movie-finder-devbyaryan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-yyUHuOvKv80iALYWdCp6Obw7oYepmE',
    appId: '1:1088035788364:ios:e2f89ad548ee469422c6e9',
    messagingSenderId: '1088035788364',
    projectId: 'movie-finder-devbyaryan',
    storageBucket: 'movie-finder-devbyaryan.firebasestorage.app',
    iosClientId: '1088035788364-q3rhmlmbd966iolbjfr6fdtjmmu8h3vm.apps.googleusercontent.com',
    iosBundleId: 'com.devbyaryan.moviefinder',
  );
}
